# Generated by Django 5.2.8 on 2025-11-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_review_review_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="review_text",
            field=models.TextField(blank=True, default=""),
        ),
    ]
