# Generated by Django 5.2.8 on 2025-11-25 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_review_review_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvergreenCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evergreen_collection",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evergreen_collection",
                        to="api.video",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "video")},
            },
        ),
        migrations.DeleteModel(
            name="VideoSave",
        ),
    ]
