# Generated by Django 5.2.8 on 2026-02-23 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_customuser_email_alter_review_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoEvergreenStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("avg_rating", models.FloatField(blank=True, null=True)),
                ("rating_count", models.PositiveIntegerField(default=0)),
                ("bookmark_count", models.PositiveIntegerField(default=0)),
                ("review_count", models.PositiveIntegerField(default=0)),
                ("review_upvote_count", models.PositiveIntegerField(default=0)),
                ("reply_count", models.PositiveIntegerField(default=0)),
                ("reply_upvote_count", models.PositiveIntegerField(default=0)),
                ("avg_watch_ratio_all_time", models.FloatField(blank=True, null=True)),
                ("completion_rate_all_time", models.FloatField(blank=True, null=True)),
                ("avg_watch_ratio_recent", models.FloatField(blank=True, null=True)),
                ("completion_rate_recent", models.FloatField(blank=True, null=True)),
                ("completion_rate_0_3m", models.FloatField(blank=True, null=True)),
                ("completion_rate_3_12m", models.FloatField(blank=True, null=True)),
                ("completion_rate_12_36m", models.FloatField(blank=True, null=True)),
                ("completion_rate_36m_plus", models.FloatField(blank=True, null=True)),
                ("creator_reputation_score", models.FloatField(blank=True, null=True)),
                ("global_evergreen_score", models.FloatField(default=0.0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "video",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evergreen_stats",
                        to="api.video",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VideoWatchEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(blank=True, max_length=64, null=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("watch_seconds", models.PositiveIntegerField(default=0)),
                ("completed", models.BooleanField(default=False)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("home", "Homepage"),
                            ("video", "Direct video page"),
                            ("search", "Search results"),
                            ("topic", "Topic page"),
                            ("external", "External / unknown"),
                        ],
                        default="video",
                        max_length=16,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="watch_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watch_events",
                        to="api.video",
                    ),
                ),
            ],
        ),
    ]
