# Generated by Django 5.2.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_videoevergreenstats_videowatchevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="notify_reply_to_review",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="weekly_digest",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="profile_private",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="hide_reviews_ratings",
            field=models.BooleanField(default=False),
        ),
    ]
